import { useState } from "react";
import { FileDown, Upload, Clock, Check, AlertTriangle, Trash2, Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface ConfigBackup {
  id: string;
  name: string;
  router: string;
  date: string;
  size: string;
  type: "manual" | "auto";
  status: "success" | "warning";
}

export function ConfigFiles() {
  const { toast } = useToast();
  const [selectedRouter, setSelectedRouter] = useState("all");

  const [backups] = useState<ConfigBackup[]>([
    { id: "1", name: "main-router-backup-2024-01-15.rsc", router: "Main Router", date: "2024-01-15 14:30", size: "48 KB", type: "manual", status: "success" },
    { id: "2", name: "branch-a-backup-2024-01-15.rsc", router: "Branch A Router", date: "2024-01-15 02:00", size: "32 KB", type: "auto", status: "success" },
    { id: "3", name: "main-router-backup-2024-01-14.rsc", router: "Main Router", date: "2024-01-14 14:30", size: "47 KB", type: "manual", status: "success" },
    { id: "4", name: "branch-b-backup-2024-01-14.rsc", router: "Branch B Router", date: "2024-01-14 02:00", size: "28 KB", type: "auto", status: "warning" },
    { id: "5", name: "main-router-backup-2024-01-13.rsc", router: "Main Router", date: "2024-01-13 14:30", size: "46 KB", type: "manual", status: "success" },
  ]);

  const handleDownload = (backup: ConfigBackup) => {
    // Create a sample RSC config content
    const configContent = `# RouterOS Configuration Backup
# Router: ${backup.router}
# Date: ${backup.date}
# Generated by HotSpot Pro

/interface bridge
add name=bridge1 protocol-mode=none

/ip pool
add name=hotspot-pool ranges=192.168.1.100-192.168.1.250

/ip dhcp-server
add address-pool=hotspot-pool interface=bridge1 name=dhcp1

/ip hotspot
add address-pool=hotspot-pool disabled=no interface=bridge1 name=hotspot1

/ip hotspot profile
set [ find default=yes ] html-directory=hotspot login-by=cookie,http-chap

# End of configuration
`;
    
    const blob = new Blob([configContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = backup.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Download Started",
      description: `Downloading ${backup.name}`,
    });
  };

  const handleCreateBackup = () => {
    toast({
      title: "Creating Backup",
      description: "Generating configuration backup...",
    });
  };

  const filteredBackups = selectedRouter === "all" 
    ? backups 
    : backups.filter(b => b.router === selectedRouter);

  const routers = [...new Set(backups.map(b => b.router))];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Config Files</h2>
          <p className="text-muted-foreground">Download and manage router configurations</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">
            <Upload className="w-4 h-4 mr-2" />
            Upload Config
          </Button>
          <Button onClick={handleCreateBackup}>
            <FileDown className="w-4 h-4 mr-2" />
            Create Backup
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <Card className="glass-card border-border">
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <FileText className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{backups.length}</p>
                <p className="text-sm text-muted-foreground">Total Backups</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="glass-card border-success/20 bg-success/5">
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-success/10 flex items-center justify-center">
                <Check className="w-5 h-5 text-success" />
              </div>
              <div>
                <p className="text-2xl font-bold text-success">{backups.filter(b => b.status === "success").length}</p>
                <p className="text-sm text-muted-foreground">Successful</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="glass-card border-border">
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <Clock className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{backups.filter(b => b.type === "auto").length}</p>
                <p className="text-sm text-muted-foreground">Auto Backups</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="glass-card border-warning/20 bg-warning/5">
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-warning/10 flex items-center justify-center">
                <AlertTriangle className="w-5 h-5 text-warning" />
              </div>
              <div>
                <p className="text-2xl font-bold text-warning">{backups.filter(b => b.status === "warning").length}</p>
                <p className="text-sm text-muted-foreground">With Issues</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Backup List */}
      <Card className="glass-card border-border">
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-foreground">Configuration Backups</CardTitle>
          <Select value={selectedRouter} onValueChange={setSelectedRouter}>
            <SelectTrigger className="w-48 bg-secondary/50 border-border">
              <SelectValue placeholder="Filter by router" />
            </SelectTrigger>
            <SelectContent className="bg-card border-border">
              <SelectItem value="all">All Routers</SelectItem>
              {routers.map((router) => (
                <SelectItem key={router} value={router}>{router}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border bg-secondary/30">
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">File Name</th>
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">Router</th>
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">Date</th>
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">Size</th>
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">Type</th>
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">Status</th>
                  <th className="text-left text-sm font-medium text-muted-foreground px-6 py-4">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredBackups.map((backup) => (
                  <tr key={backup.id} className="border-b border-border/50 hover:bg-secondary/20 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <FileText className="w-4 h-4 text-primary" />
                        <code className="font-mono text-sm text-foreground">{backup.name}</code>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-foreground">{backup.router}</td>
                    <td className="px-6 py-4 text-sm text-muted-foreground">{backup.date}</td>
                    <td className="px-6 py-4 text-sm text-foreground">{backup.size}</td>
                    <td className="px-6 py-4">
                      <Badge variant="outline" className={backup.type === "auto" ? "text-primary border-primary/30" : "text-muted-foreground border-muted"}>
                        {backup.type}
                      </Badge>
                    </td>
                    <td className="px-6 py-4">
                      {backup.status === "success" ? (
                        <Badge variant="outline" className="text-success border-success/30">
                          <Check className="w-3 h-3 mr-1" />
                          Success
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="text-warning border-warning/30">
                          <AlertTriangle className="w-3 h-3 mr-1" />
                          Warning
                        </Badge>
                      )}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex gap-2">
                        <Button 
                          variant="ghost" 
                          size="icon"
                          onClick={() => handleDownload(backup)}
                        >
                          <Download className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive">
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Auto Backup Settings */}
      <Card className="glass-card border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-foreground">
            <Clock className="w-5 h-5 text-primary" />
            Automatic Backup Schedule
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-medium text-foreground">Backup Frequency</label>
              <Select defaultValue="daily">
                <SelectTrigger className="bg-secondary/50 border-border">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-card border-border">
                  <SelectItem value="hourly">Every Hour</SelectItem>
                  <SelectItem value="daily">Daily</SelectItem>
                  <SelectItem value="weekly">Weekly</SelectItem>
                  <SelectItem value="monthly">Monthly</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-foreground">Time</label>
              <Select defaultValue="02:00">
                <SelectTrigger className="bg-secondary/50 border-border">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-card border-border">
                  <SelectItem value="00:00">12:00 AM</SelectItem>
                  <SelectItem value="02:00">2:00 AM</SelectItem>
                  <SelectItem value="04:00">4:00 AM</SelectItem>
                  <SelectItem value="06:00">6:00 AM</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-foreground">Retention</label>
              <Select defaultValue="30">
                <SelectTrigger className="bg-secondary/50 border-border">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-card border-border">
                  <SelectItem value="7">7 Days</SelectItem>
                  <SelectItem value="14">14 Days</SelectItem>
                  <SelectItem value="30">30 Days</SelectItem>
                  <SelectItem value="90">90 Days</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <Button className="mt-6">Save Schedule</Button>
        </CardContent>
      </Card>
    </div>
  );
}
